### ISSUE TITLE
Basic Todo List Functionality

### ISSUE THREAD

**Issue by scottpchow23** [scottpchow23/Spring-Todo#3]
### User Story
As a user, I should be able to visit the base page and:

- [x] Create a new todo list item
- [x] Complete an existing todo list item
- [x] Delete todo list item

### Dev Notes

- This will require persisting data. A combo of JPA with Postgres should do the trick.
- This will likely involve the add, update, and delete functions for a task redirecting back to the base url.
